lous changes on glpk setup

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -472,7 +472,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS ADDLIBS FADDLIBS ALWAYS_FALSE_TRUE ALWAYS_FALSE_FALSE build build_cpu build_vendor build_os CDEFS ADD_CFLAGS DBG_CFLAGS OPT_CFLAGS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT MPICC EGREP INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBTOOLM4 have_autoconf have_automake have_svn BUILDTOOLSDIR AUX_DIR abs_source_dir abs_lib_dir abs_include_dir abs_bin_dir HAVE_EXTERNALS_TRUE HAVE_EXTERNALS_FALSE host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL ac_c_preproc_warn_flag ac_cxx_preproc_warn_flag RPATH_FLAGS LT_LDFLAGS GLPKINCDIR GLPKLIB COIN_HAS_GLPK_TRUE COIN_HAS_GLPK_FALSE GLPKCOINLIB COIN_BUILD_GLPK_TRUE COIN_BUILD_GLPK_FALSE MAKEOKFILE SKIPMAKE_TRUE SKIPMAKE_FALSE GLPKDIR LIBEXT VPATH_DISTCLEANFILES LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS ADDLIBS FADDLIBS ALWAYS_FALSE_TRUE ALWAYS_FALSE_FALSE build build_cpu build_vendor build_os CDEFS ADD_CFLAGS DBG_CFLAGS OPT_CFLAGS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT MPICC EGREP INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBTOOLM4 have_autoconf have_automake have_svn BUILDTOOLSDIR AUX_DIR abs_source_dir abs_lib_dir abs_include_dir abs_bin_dir HAVE_EXTERNALS_TRUE HAVE_EXTERNALS_FALSE host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL ac_c_preproc_warn_flag ac_cxx_preproc_warn_flag RPATH_FLAGS LT_LDFLAGS GLPKINCDIR GLPKLIB COIN_HAS_GLPK_TRUE COIN_HAS_GLPK_FALSE COIN_BUILD_GLPK_TRUE COIN_BUILD_GLPK_FALSE MAKEOKFILE GLPKDIR LIBEXT VPATH_DISTCLEANFILES LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -19710,6 +19710,11 @@ else
 fi
 coin_glpksrcdir=$abs_source_dir/$coin_glpkobjdir
 
+use_thirdpartyglpk=no
+
+# Check for the requested component. If the user specified an external glpk
+# library don't force a ThirdParty build, let the error propagate.
+
 
   echo "$as_me:$LINENO: checking if user provides library for Glpk" >&5
 echo $ECHO_N "checking if user provides library for Glpk... $ECHO_C" >&6
@@ -19893,44 +19898,65 @@ else
 fi
 
 
+ if test x"$coin_has_glpk" = xfalse && test x"$GLPKLIB" = x ; then
+   use_thirdpartyglpk=try
+ fi
 
-MAKEOKFILE=.MakeOk
-use_glpk="$GLPKLIB"
-if test "$GLPKLIB" == ""; then
 
+# If the user has supplied an external library, use it. Otherwise, consider
+# a build in ThirdParty/Glpk. If we build, assume we get both glpk and gmpl.
+
+if test x"$use_thirdpartyglpk" = xtry ; then
+  MAKEOKFILE=.MakeOk
   # Check if the Glpk's ThirdParty project has been configured
   if test "$PACKAGE_NAME" != ThirdPartyGlpk; then
     if test -r $coin_glpkobjdir/.MakeOk; then
-      use_glpk=BUILD
+      use_thirdpartyglpk=build
+    else
+      use_thirdpartyglpk=no
     fi
+  else
+    use_thirdpartyglpk=build
   fi
-fi
 
-if test x"$use_glpk" == xBUILD; then
+# If we're building, set the library and include directory variables, create a
+# preprocessor symbol, define a variable that says we're using glpk/gmpl, and
+# another to indicate a link check is a bad idea (hard to do before the library
+# exists).
 
-  GLPKCOINLIB=`cd $coin_glpkobjdir; pwd`/libcoinglpk.la
+  if test x"$use_thirdpartyglpk" == xbuild ; then
+    GLPKLIB=`cd $coin_glpkobjdir; pwd`/libcoinglpk.la
 
+    ADDLIBS="$GLPKLIB $ADDLIBS"
+    GLPKINCDIR="$coin_glpksrcdir/glpk/include"
 
-  GLPKINCDIR="$coin_glpksrcdir/glpk/include"
 
 cat >>confdefs.h <<\_ACEOF
 #define COIN_HAS_GLPK 1
 _ACEOF
 
+    coin_has_glpk=true
+    glpk_libcheck=no
+    { echo "$as_me:$LINENO: Using Glpk in ThirdParty/Glpk" >&5
+echo "$as_me: Using Glpk in ThirdParty/Glpk" >&6;}
+  fi
+fi
 
-  # This is a "true" for AM_CONDITIONAL(COIN_HAS_GLPK)
+# Define the necessary automake conditionals.
+
+
+
+if test x"$coin_has_glpk" = xtrue; then
   COIN_HAS_GLPK_TRUE=
   COIN_HAS_GLPK_FALSE='#'
-
-  coin_has_glpk=yes
-
-  { echo "$as_me:$LINENO: Using Glpk in ThirdParty" >&5
-echo "$as_me: Using Glpk in ThirdParty" >&6;}
+else
+  COIN_HAS_GLPK_TRUE='#'
+  COIN_HAS_GLPK_FALSE=
 fi
 
 
 
-if test x"$use_glpk" = xBUILD; then
+if test x"$use_thirdpartyglpk" = xbuild; then
   COIN_BUILD_GLPK_TRUE=
   COIN_BUILD_GLPK_FALSE='#'
 else
@@ -19942,22 +19968,17 @@ fi
 
 
 rm -f $MAKEOKFILE
-if test $coin_has_glpk = yes && test "$use_glpk" != BUILD; then
-  { echo "$as_me:$LINENO: The Glpk sources don't need to be compiled" >&5
-echo "$as_me: The Glpk sources don't need to be compiled" >&6;}
-  MAKEOKFILE=
-else
+if test x"$use_thirdpartyglpk" = xbuild ; then
   touch $MAKEOKFILE
-fi
-
-
-
-if test -z "$MAKEOKFILE"; then
-  SKIPMAKE_TRUE=
-  SKIPMAKE_FALSE='#'
 else
-  SKIPMAKE_TRUE='#'
-  SKIPMAKE_FALSE=
+  if test x$coin_has_glpk = xtrue ; then
+    { echo "$as_me:$LINENO: The Glpk sources don't need to be compiled" >&5
+echo "$as_me: The Glpk sources don't need to be compiled" >&6;}
+  else
+    { echo "$as_me:$LINENO: WARNING: Glpk source is available but will not be built. No valid external library is detected. Are you sure this is what you want?" >&5
+echo "$as_me: WARNING: Glpk source is available but will not be built. No valid external library is detected. Are you sure this is what you want?" >&2;}
+  fi
+  MAKEOKFILE=
 fi
 
 
@@ -20195,17 +20216,17 @@ echo "$as_me: error: conditional \"COIN_HAS_GLPK\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${COIN_HAS_GLPK_TRUE}" && test -z "${COIN_HAS_GLPK_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"COIN_HAS_GLPK\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"COIN_HAS_GLPK\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${COIN_BUILD_GLPK_TRUE}" && test -z "${COIN_BUILD_GLPK_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"COIN_BUILD_GLPK\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"COIN_BUILD_GLPK\" was never defined.
-Usually this means the macro was only invoked conditionally." >&2;}
-   { (exit 1); exit 1; }; }
-fi
-if test -z "${SKIPMAKE_TRUE}" && test -z "${SKIPMAKE_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"SKIPMAKE\" was never defined.
-Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"SKIPMAKE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -20831,12 +20852,9 @@ s,@GLPKINCDIR@,$GLPKINCDIR,;t t
 s,@GLPKLIB@,$GLPKLIB,;t t
 s,@COIN_HAS_GLPK_TRUE@,$COIN_HAS_GLPK_TRUE,;t t
 s,@COIN_HAS_GLPK_FALSE@,$COIN_HAS_GLPK_FALSE,;t t
-s,@GLPKCOINLIB@,$GLPKCOINLIB,;t t
 s,@COIN_BUILD_GLPK_TRUE@,$COIN_BUILD_GLPK_TRUE,;t t
 s,@COIN_BUILD_GLPK_FALSE@,$COIN_BUILD_GLPK_FALSE,;t t
 s,@MAKEOKFILE@,$MAKEOKFILE,;t t
-s,@SKIPMAKE_TRUE@,$SKIPMAKE_TRUE,;t t
-s,@SKIPMAKE_FALSE@,$SKIPMAKE_FALSE,;t t
 s,@GLPKDIR@,$GLPKDIR,;t t
 s,@LIBEXT@,$LIBEXT,;t t
 s,@VPATH_DISTCLEANFILES@,$VPATH_DISTCLEANFILES,;t t
